### ISSUE TITLE
Incorrect link redirecting to google internal pantheon

### ISSUE THREAD

**Issue by seagomezar** [googlecodelabs/maps-platform-deckgl#7]
Hi, @amuramoto !!! I hope you are great!

I found an error in the codelab text: https://codelabs.developers.google.com/codelabs/maps-deck-gl/index.html?index=..%2F..index#2

As you may see in the image below, the link to the cloud console is redirecting incorrectly to pantheon...
<img width="852" alt="incorrect link" src="https://user-images.githubusercontent.com/2058936/93408257-b8893900-f859-11ea-8a71-6aba60ba9f38.png">

Let me know if you need help to fix this issue if you give me access to the source of the codelab!

Cheers!

**Comment by amuramoto** [comment]
Thanks for catching this! Apologies for the slow response - didn't see the GH notification for this one.
